SEGUNDO_EJERCICIO_CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path
from personas.views import home_view, list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('listado/', list_view, name='listado'),
]

SEGUNDO_EJERCICIO_CRUD/personas/models.py
from django.db import models

class Persona(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=True)
    nombre = models.TextField(max_length=500, blank=False)
    apellido = models.TextField(max_length=500, blank=False)
    dni = models.PositiveIntegerField(default=0)
    fecha_nac = models.DateField(blank=False)

SEGUNDO_EJERCICIO_CRUD/personas/forms.py
from django import forms


class PersonaForm(forms.Form):
        nombre = forms.CharField()
        apellido = forms.CharField()
        dni = forms.IntegerField(min_value=0)
        fecha_nac = forms.CharField(widget=forms.TextInput(attrs={"class": "datepicker"}))

SEGUNDO_EJERCICIO_CRUD/personas/views.py
import datetime
from django.shortcuts import render
from .models import Persona
from .forms import PersonaForm
from dateutil.relativedelta import relativedelta


def home_view(request):
    form = PersonaForm()
    if request.method == "POST":
        form = PersonaForm(request.POST or None)
        if form.is_valid():
            Persona.objects.create(**form.cleaned_data)
            form = PersonaForm()
        else:
            print(form.errors)
    context = {"form": form}
    return render(request, "personas_home.html", context)


def list_view(request):
    fecha_ref_25 = datetime.datetime.now() - relativedelta(years=25)
    fecha_ref_35 = datetime.datetime.now() - relativedelta(years=35)
    personas_en_db = Persona.objects.filter(fecha_nac__lte=fecha_ref_25).filter(fecha_nac__gte=fecha_ref_35)
    context = {"personas": personas_en_db}
    return render(request, "personas_listado.html", context)

SEGUNDO_EJERCICIO_CRUD/personas/templates/personas_home.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-vert-center">
    <div class="row">
        <div class="col s12 center-align">
            <h3>WES-IT</h3>
        </div>
    </div>
    <div class="row">
        <form class="col s12" action="." method="POST">{% csrf_token %}

            <div class="row">

                <div class="input-field col s6">
                    {{form.nombre}}
                    <label for="id_nombre">Nombre</label>
                </div>

                <div class="input-field col s6">
                    {{form.apellido}}
                    <label for="id_apellido">Apellido</label>
                </div>

            </div>



            <div class="row">

                <div class="input-field col s6">
                    {{form.fecha_nac}}
                    <label for="id_fecha_nac">Fecha de Nacimiento</label>
                </div>

                <div class="input-field col s6">
                    {{form.dni}}
                    <label for="id_dni">DNI</label>
                </div>

            </div>



            <div class="row">
                <div class="input-field col s12 center-align">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>



        </form>
    </div>
</div>

{% endblock %}

SEGUNDO_EJERCICIO_CRUD/personas/templates/personas_listado.html
{% extends 'layout.html' %}

{% block content %}


<div class="container">


    <div class="row center-align">
        <h4>Tienen entre 25 y 35 años</h4>
    </div>


    <div class="row">
    </div>


    <div class="row">
        <div class="col s12">
            <table class="responsive-table highlight">
                {% for persona in personas %}
                <tr>
                    <td>
                        {{persona.nombre}}
                    </td>
                    <td>
                        {{persona.apellido}}
                    </td>
                    <td>
                        {{persona.fecha_nac}}
                    </td>
                    <td>
                        {{persona.dni}}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>


{% endblock %}

SEGUNDO_EJERCICIO_CRUD/templates/layout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TryDjango App</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" media="screen,projection">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    <div class="main-grid">
        <header>
            <nav>
                <div class="nav-wrapper">
                    <span class="brand-logo right">Pablo Yacoli</span>
                    <ul id="nav-mobile" class="left hide-on-med-and-down">
                        <li><a href="http://127.0.0.1:8000/">Formulario</a></li>
                        <li><a href="http://127.0.0.1:8000/listado">Edades entre 25 y 35</a></li>
                    </ul>
                </div>
            </nav>
        </header>

        <content>
            {% block content %}
            {% endblock %}
        </content>

        <footer>
            <div>
            </div>
        </footer>

    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'main.js' %}"></script>
</body>
</html>